# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 564)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Car_ID = QtWidgets.QTextEdit(self.centralwidget)
        self.Car_ID.setGeometry(QtCore.QRect(60, 59, 311, 181))
        self.Car_ID.setObjectName("Car_ID")
        self.Person_ID = QtWidgets.QTextEdit(self.centralwidget)
        self.Person_ID.setGeometry(QtCore.QRect(60, 259, 311, 171))
        self.Person_ID.setObjectName("Person_ID")
        self.Process = QtWidgets.QPushButton(self.centralwidget)
        self.Process.setGeometry(QtCore.QRect(60, 439, 141, 51))
        self.Process.setObjectName("Process")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(230, 439, 141, 51))
        self.ExitButton.setObjectName("ExitButton")
        self.Status_Text = QtWidgets.QLabel(self.centralwidget)
        self.Status_Text.setGeometry(QtCore.QRect(60, 501, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Status_Text.setFont(font)
        self.Status_Text.setAcceptDrops(False)
        self.Status_Text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Status_Text.setAlignment(QtCore.Qt.AlignCenter)
        self.Status_Text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.Status_Text.setObjectName("Status_Text")
        self.Status_Text_2 = QtWidgets.QLabel(self.centralwidget)
        self.Status_Text_2.setEnabled(True)
        self.Status_Text_2.setGeometry(QtCore.QRect(30, 10, 371, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Status_Text_2.setFont(font)
        self.Status_Text_2.setAcceptDrops(False)
        self.Status_Text_2.setToolTip("")
        self.Status_Text_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Status_Text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Status_Text_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.Status_Text_2.setObjectName("Status_Text_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 433, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LINE訊息轉Google Sheet"))
        self.Car_ID.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Car_ID.setPlaceholderText(_translate("MainWindow", "<輸入車號、車次等資訊>"))
        self.Person_ID.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Person_ID.setPlaceholderText(_translate("MainWindow", "<輸入車號、人名等資訊>"))
        self.Process.setText(_translate("MainWindow", "轉換並上傳"))
        self.ExitButton.setText(_translate("MainWindow", "關閉程式"))
        self.Status_Text.setWhatsThis(_translate("MainWindow", "目前程式執行狀態"))
        self.Status_Text.setText(_translate("MainWindow", "閒置..."))
        self.Status_Text_2.setText(_translate("MainWindow", "Line訊息轉Google試算表"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
